excludes = [
    ['{home}', 'exclude', 'path']
]

# case-insensitive excludes
iexcludes = []

includePatterns = []
includePaths = []

repositoryPath = []
usbRepositoryPath = []

repositoryPassword = 'restic'
usbRepositoryPassword = 'restic'

[placeholders]
home = '/home/username'
driveC = 'C:'
