excludes = [
    ['{home}', 'exclude', 'path']
]

# case-insensitive excludes
iexcludes = []

includePatterns = []
includePaths = []

repositoryPath = ['path', 'to', 'repo']
usbRepositoryPath = []

repositoryPassword = 'restic'
usbRepositoryPassword = 'restic'

resticPath = []

[placeholders]
home = '/home/username'
driveC = 'C:'
